### ISSUE TITLE
成功運行，但要怎麼讓他搶購？

### ISSUE THREAD

**Issue by botio** [jumpingchu/PChome-AutoBuy#1]
看起來視窗執行一次後 就停在那邊，如果遇到 ”尚未開賣“ 就沒有繼續執行？
有辦法讓他重複執行嗎？（每30秒？）

**Comment by sheway** [comment]
可以藉由抓取封包來判斷那件商品是否開賣，我的作法是時間到後重複要求伺服器該商品的商品狀態，但 pchome 有偵測機制，大約7~9次後就會不讓你拿了。如果是想看該商品是否有貨，可參考Jia大的IT空間。

**Comment by botio** [comment]
https://blog.jiatool.com/posts/pchome_spider01/

**Comment by sheway** [comment]
是的~

**Comment by jumpingchu** [comment]
@botio 

1. 尚未開賣的話，可以先以別的相似商品做測試
2. 每30秒重複執行的部分可以寫個 loop 加上 try/except 搭配 time.sleep(30) 的方式去做

**Comment by jumpingchu** [comment]
@sheway 
抓封包也是一個方式，但就怕很快會被限制或被鎖之類的問題，我個人是還沒有試過
感謝您提供的方法與參考資料！

**Comment by botio** [comment]
重點就是2. loop. (句號）
