### ISSUE TITLE
使用教學

### ISSUE THREAD

**Issue by richard99580** [jumpingchu/PChome-AutoBuy#13]
請問有詳細教學嗎    
程式新手我只把Zip檔下載後用python開編輯個人資料就不會用了..謝謝您`

**Comment by jumpingchu** [comment]
你好：
只有在settings.py填資料時才需要用到編輯器唷！
其他我在主頁所寫的都是在 Terminal/cmd 上面執行的
詳細教學可以參考一下 README.md 裡面的使用方式，謝謝！
