### ISSUE TITLE
因作業需求需要授權詢問

### ISSUE THREAD

**Issue by sheway** [jumpingchu/PChome-AutoBuy#2]
您好，我是元智大學的學生，因為教授的作業需求關係，有使用到您的 project，而教授需要我們將整個 project 上傳至 GitHub，所以想詢問這個部分是否能授權我作為作業用途，上傳至自己的 GitHub 頁面，並且會在 README 部分提及您的原始專案呢？

目前我有加入其他功能，像是使用 cookie 登入、設定時間讓腳本自動執行、加入預防 PChome 的時差機制、改善有時無法按到購物車按鈕的問題。

**Comment by jumpingchu** [comment]
@sheway 您好，很開心這個 project 有幫助到您，引用時有在 README 提及的話都很歡迎！

**Comment by botio** [comment]
> 您好，我是元智大學的學生，因為教授的作業需求關係，有使用到您的 project，而教授需要我們將整個 project 上傳至 GitHub，所以想詢問這個部分是否能授權我作為作業用途，上傳至自己的 GitHub 頁面，並且會在 README 部分提及您的原始專案呢？
> 
> 目前我有加入其他功能，像是使用 cookie 登入、設定時間讓腳本自動執行、加入預防 PChome 的時差機制、改善有時無法按到購物車按鈕的問題。

請問這些新加入的功能 有要開源出來嗎？ （fork?)

**Comment by jumpingchu** [comment]
@botio
是否開源這部分要看 @sheway 願不願意把功能開個 PR 上來
我是希望每個人都能自己搶到自己想要的商品、杜絕黃牛，所以功能越完整越好

**Comment by sheway** [comment]
@jumpingchu 好的非常感謝~
@botio 會的喔

**Comment by sheway** [comment]
@botio 
我剛剛重新看了我的code
發現被我改的很多
所以不會發pr回去
但會放在我的頁面
歡迎來form~

**Comment by botio** [comment]
> @botio
> 我剛剛重新看了我的code
> 發現被我改的很多
> 所以不會發pr回去
> 但會放在我的頁面
> 歡迎來form~

Nice, the whole structure is way clear. GJ.

**Comment by jumpingchu** [comment]
@sheway 
有些新功能看起來不錯，之後有空我測試看看，如果OK的話，我自己更新一下，然後會在專案提及你為contributer，這樣的方式可以嗎？

**Comment by sheway** [comment]
@jumpingchu  好啊好啊
我不發pr回去是覺得我跟你寫的格式差蠻多的
若你覺得沒關係我也可以發pr回去～

**Comment by jumpingchu** [comment]
> @jumpingchu  好啊好啊
> 
> 我不發pr回去是覺得我跟你寫的格式差蠻多的
> 
> 若你覺得沒關係我也可以發pr回去～

那我這邊就自己更新，之後你有新功能歡迎隨時再發 Issue 哦～
