### ISSUE TITLE
記住登入資訊

### ISSUE THREAD

**Issue by derekdonyen** [jumpingchu/PChome-AutoBuy#8]
已經照您文中的建議設定

settings.py 內的 CHROME_PATH 可讓 chrome 記住登入資訊，可提升搶購速度，建議使用

但是每次都需要重新登入，請問是哪邊還需要注意? 謝謝。

**Comment by jumpingchu** [comment]
@derekdonyen 你好，以下提供我所知道的幾種可能性：
1. **確認反斜線（左上右下）**
    * Windows 的設定檔路徑應該長這樣 `C:\Users\<UserName>\AppData\Local\Google\Chrome\User Data\Default`

2. **試試看雙反斜線**
    * `C:\\Users\\<UserName>\\AppData\\Local\\Google\\Chrome\\User Data\\Default`

3. **編碼問題**
    * 試著將空格改為 `%20`（如 `\User Data\` => `\User%20Data\`）

4. 確認登入畫面有勾選"記住帳號"（理論上頁面預設會是勾選的）

**Comment by derekdonyen** [comment]
謝謝，問題已經解決。
